"""add_reading_progress_and_preferences_to_user

Revision ID: 7791095a9a4f
Revises: d47cd8f58bb3
Create Date: 2025-12-03 05:46:22.209533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7791095a9a4f'
down_revision: Union[str, None] = 'd47cd8f58bb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Don't drop conversations and messages tables - they're needed
    # op.drop_index('ix_conversations_user_id', table_name='conversations')
    # op.drop_table('conversations')
    # op.drop_index('ix_messages_conversation_id', table_name='messages')
    # op.drop_index('ix_messages_timestamp', table_name='messages')
    # op.drop_table('messages')
    op.add_column('users', sa.Column('reading_progress', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('learning_level', sa.String(), nullable=True))
    op.add_column('users', sa.Column('preferences', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferences')
    op.drop_column('users', 'learning_level')
    op.drop_column('users', 'reading_progress')
    # Don't recreate conversations and messages tables
    # ### end Alembic commands ###
