import * as fs from 'fs/promises';
import * as path from 'path';
import { parse } from 'toml';
import * as dotenv from 'dotenv';

// Load environment variables
dotenv.config();

interface ChapterSpec {
  id: string;
  title: string;
  prompt: string;
}

interface BookSpec {
  book: {
    title: string;
    author: string;
  };
  chapters: ChapterSpec[];
}

async function main() {
  try {
    // Read the book specification
    const specContent = await fs.readFile('book_spec.toml', 'utf-8');
    const bookSpec: BookSpec = parse(specContent);

    // Create directory if it doesn't exist
    const outputDir = '../book-ui/docs';
    await fs.mkdir(outputDir, { recursive: true });

    console.log(`Generating ${bookSpec.chapters.length} chapters...`);

    // For each chapter, we would normally call an AI service to generate content
    // For now, we'll create placeholder content based on the prompts
    for (const chapter of bookSpec.chapters) {
      const content = `---
sidebar_position: 1
slug: /${chapter.id}
---

# ${chapter.title}

${chapter.prompt}

:::info Chapter Overview
This content was automatically generated by the spec-engine based on the following prompt:
${chapter.prompt}
:::

## Learning Objectives

After reading this chapter, you will understand:

- Key concepts related to this topic
- Practical applications and examples
- Implementation considerations

## Key Concepts

### Main Topic 1

Detailed explanation of the first key concept with examples.

### Main Topic 2

Detailed explanation of the second key concept with examples.

### Main Topic 3

Detailed explanation of the third key concept with examples.

## Practical Examples

Real-world applications and code examples demonstrating the concepts.

## Summary

Brief summary of the main topics covered in this chapter.

---

**Next Chapter**: [Next chapter title and link]
`;

      const filePath = path.join(outputDir, `${chapter.id}.md`);
      await fs.writeFile(filePath, content);
      console.log(`Generated: ${filePath}`);
    }

    console.log('Book generation completed!');
  } catch (error) {
    console.error('Error generating book:', error);
  }
}

main();