import clsx from "clsx";
import Link from "@docusaurus/Link";
import useDocusaurusContext from "@docusaurus/useDocusaurusContext";
import ChatWidget from "../components/ChatWidget";
import Layout from "@theme/Layout";
import Heading from "@theme/Heading";
import styles from "./index.module.css";
import { JSX } from "react";

function HomepageHeader() {
  const { siteConfig } = useDocusaurusContext();
  return (
    <header
      className={clsx("hero", "heroBanner")}
      style={{
        padding: "6rem 0",
        background: "transparent",
        position: "relative",
        overflow: "hidden",
      }}
    >
      {/* Background Glow Effect */}
      <div
        style={{
          position: "absolute",
          top: "50%",
          left: "50%",
          transform: "translate(-50%, -50%)",
          width: "80%",
          height: "80%",
          background:
            "radial-gradient(circle, rgba(37,194,160,0.08) 0%, transparent 70%)",
          zIndex: 0,
          pointerEvents: "none",
        }}
      ></div>

      <div
        className="container"
        style={{
          position: "relative",
          zIndex: 1,
          display: "flex",
          flexDirection: "column",
          alignItems: "center" /* Horizontal Center */,
          justifyContent: "center",
          textAlign: "center",
        }}
      >
        {/* Title */}
        <Heading as="h1" className="hero__title">
          <span
            style={{
              background: "linear-gradient(to right, #fff, #25c2a0)",
              WebkitBackgroundClip: "text",
              WebkitTextFillColor: "transparent",
              fontSize: "5rem" /* Increased Size */,
              fontWeight: 800,
              filter: "drop-shadow(0 0 25px rgba(37,194,160,0.4))",
              lineHeight: 1.1,
            }}
          >
            {siteConfig.title}
          </span>
        </Heading>

        {/* Subtitle */}
        <p
          className="hero__subtitle"
          style={{
            fontSize: "2rem",
            marginTop: "0.5rem",
            color: "#25c2a0",
            fontWeight: "600",
            letterSpacing: "1px",
          }}
        >
          {siteConfig.tagline}
        </p>

        {/* NEW: Description Text */}
        <p
          style={{
            maxWidth: "800px" /* Width limit taake text fail na jaye */,
            fontSize: "1.2rem",
            lineHeight: "1.6",
            color: "#cbd5e1" /* Soft White/Grey */,
            marginTop: "1.5rem",
            marginBottom: "3rem",
          }}
        >
          Welcome to the cutting-edge platform where{" "}
          <strong>Specification-Driven Development</strong> meets{" "}
          <strong>Artificial Intelligence</strong>. This book is generated by AI
          agents, strictly following architectural specs, and features an
          embedded
          <strong> RAG Chatbot</strong> to answer your questions directly from
          the content.
        </p>

        {/* Buttons */}
        <div
          className={styles.buttons}
          style={{
            display: "flex",
            gap: "2rem",
            justifyContent: "center",
            flexWrap: "wrap",
          }}
        >
          {/* Animated Neon Button 1 */}
          <Link to="/docs/Deep Intro" className="neon-button">
            <span>Start Reading 📘</span>
          </Link>

          {/* Animated Neon Button 2 */}
          <Link
            to="https://github.com/rabiasohail098/ai-driven-spec-book"
            className="neon-button"
          >
            <span>GitHub Repo 💻</span>
          </Link>

          {/* Auth Buttons */}
          <Link to="/signup" className="neon-button">
            <span>Join Now 👥</span>
          </Link>
        </div>
      </div>
    </header>
  );
}

export default function Home(): JSX.Element {
  const { siteConfig } = useDocusaurusContext();
  return (
    <Layout title={`${siteConfig.title}`} description="AI Driven Spec Book">
      <HomepageHeader />
      <ChatWidget />

      <main>
        <div className="container" style={{ padding: "4rem 0" }}>
          <div className="row">
            {/* Card 1 */}
            <div className="col col--4">
              <div className="neon-border-box" style={{ height: "100%" }}>
                <div className="feature-card-content">
                  <div style={{ fontSize: "3rem", marginBottom: "1rem" }}>
                    📘
                  </div>
                  <h3 style={{ color: "#25c2a0" }}>Spec-Driven</h3>
                  <p style={{ color: "#cbd5e1" }}>
                    Architecture defined by clear specifications. The system is
                    built ensuring robust standards before a single line of code
                    is written.
                  </p>
                </div>
              </div>
            </div>

            {/* Card 2 */}
            <div className="col col--4">
              <div className="neon-border-box" style={{ height: "100%" }}>
                <div className="feature-card-content">
                  <div style={{ fontSize: "3rem", marginBottom: "1rem" }}>
                    🤖
                  </div>
                  <h3 style={{ color: "#25c2a0" }}>AI-Generated</h3>
                  <p style={{ color: "#cbd5e1" }}>
                    Content curated and written by advanced LLMs using prompt
                    engineering to ensure high-quality technical documentation.
                  </p>
                </div>
              </div>
            </div>

            {/* Card 3 */}
            <div className="col col--4">
              <div className="neon-border-box" style={{ height: "100%" }}>
                <div className="feature-card-content">
                  <div style={{ fontSize: "3rem", marginBottom: "1rem" }}>
                    🧠
                  </div>
                  <h3 style={{ color: "#25c2a0" }}>RAG Chatbot</h3>
                  <p style={{ color: "#cbd5e1" }}>
                    Embedded intelligent agent. Ask questions directly from the
                    book content and get context-aware answers instantly.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </Layout>
  );
}
